### ISSUE TITLE
Scrolling bug

### ISSUE THREAD

**Issue by artfulalibi** [enriquez/ezpz-tooltip#1]
Let me start by saying, this is by far my favorite tooltip plugin, and I love it.

I noticed that there is a little bug when keeping the mouse still and scrolling (such as by mouse wheel) over a target div. Because the mouse hasn't moved the plugin can't/doesn't calculate the location, so the popup box ends up in the top left corner. I wish it would not turn the display:block. Which would be a pleasant degrade. Or better yet, correctly calculate the locate. 

PS. you can only see this from after refresh and before moving your mouse over any tooltip. 

I hope that made sense.

**Comment by enriquez** [comment]
Thanks!

After a quick test I haven't been able to reproduce the problem.  I'm trying it on my demo here: http://theezpzway.com/2009/3/17/ezpz-tooltip-demo.

Can you provide any more details to the problem? Which browser are you using?

**Comment by artfulalibi** [comment]
You are right! So I did more digging. The error only occurs if it is inside a .clearfix. 
Link to clearfix documentation:
http://www.positioniseverything.net/easyclearing.html

Real bummer. Everyone is moving toward using this method of clearing. It makes life so much easier.
